# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'youjinLicaiCalculator' do
 
   pod 'AFNetworking', '~> 3.1.0'
   pod 'MJExtension', '~> 3.0.13'
   pod 'IQKeyboardManager'
   pod 'UMengAnalytics'
   pod 'ShareSDK3'
   pod 'ShareSDK3/ShareSDKPlatforms/QQ'
   pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
   pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
   pod 'MobLink', '~>2.0.0'
   pod 'SMSSDK'
   pod 'BaiduMobStat'
end
